add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;    
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin" always;
add_header X-Frame-Options "DENY" always;
add_header Permissions-Policy "accelerometer=(),autoplay=(),camera=(),display-capture=(),document-domain=(),encrypted-media=(),fullscreen=(self),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),screen-wake-lock=(),sync-xhr=(self),usb=(),web-share=(),xr-spatial-tracking=()" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;
add_header Cross-Origin-Embedder-Policy "require-corp" always;

set $DEFAULT "default-src 'none'";

set $FRAME "frame-src 'self'";
set $FRAME "${FRAME} https://*.configcat.com";

set $SCRIPT "script-src 'self' 'unsafe-inline'";
set $SCRIPT "${SCRIPT} https://*.configcat.com";
set $SCRIPT "${SCRIPT} https://*.cloudflareinsights.com";
set $SCRIPT "${SCRIPT} https://*.doubleclick.net";
set $SCRIPT "${SCRIPT} https://*.googletagmanager.com";
set $SCRIPT "${SCRIPT} https://googletagmanager.com";
set $SCRIPT "${SCRIPT} https://tagmanager.google.com";
set $SCRIPT "${SCRIPT} https://*.google-analytics.com";

set $STYLE "style-src 'self' 'unsafe-inline'";
set $STYLE "${STYLE} https://fonts.gstatic.com";
set $STYLE "${STYLE} https://fonts.googleapis.com";
set $STYLE "${STYLE} https://googletagmanager.com";
set $STYLE "${STYLE} https://tagmanager.google.com";
set $STYLE "${STYLE} https://*.typekit.net";
set $STYLE "${STYLE} https://www.googletagmanager.com";

set $FONT "font-src 'self' data:";
set $FONT "${FONT} https://fonts.gstatic.com";
set $FONT "${FONT} https://fonts.googleapis.com";
set $FONT "${FONT} https://*.typekit.net";

set $IMG "img-src 'self' data:";
set $IMG "${IMG} https://*.configcat.com";
set $IMG "${IMG} https://*.google-analytics.com";
set $IMG "${IMG} https://*.google.com";
set $IMG "${IMG} https://*.google.hu";
set $IMG "${IMG} https://*.googletagmanager.com";
set $IMG "${IMG} https://googletagmanager.com";
set $IMG "${IMG} https://*.gstatic.com";
set $IMG "${IMG} https://*.analytics.google.com";
set $IMG "${IMG} https://*.g.doubleclick.net";

set $CONNECT "connect-src 'self'";
set $CONNECT "${CONNECT} https://*.configcat.com";
set $CONNECT "${CONNECT} https://*.cloudflareinsights.com";
set $CONNECT "${CONNECT} https://*.amplitude.com";
set $CONNECT "${CONNECT} https://*.googletagmanager.com";
set $CONNECT "${CONNECT} https://*.google-analytics.com";
set $CONNECT "${CONNECT} https://*.analytics.google.com";
set $CONNECT "${CONNECT} https://*.doubleclick.net";
set $CONNECT "${CONNECT} https://*.google.com";
set $CONNECT "${CONNECT} https://*.google.hu";
# CONNECTPLACEHOLDER

set $OBJECT "object-src 'none'";

set $CHILD "child-src 'self' blob:";

set $FRAMEANC "frame-ancestors https://*.configcat.com";

set $MISC "upgrade-insecure-requests; block-all-mixed-content";

add_header Content-Security-Policy "${DEFAULT}; ${FRAME}; ${SCRIPT}; ${STYLE}; ${FONT}; ${IMG}; ${CONNECT}; ${OBJECT}; ${CHILD}; ${FRAMEANC}; ${MISC}" always;
